### to create the wallet
POST http://localhost:5000/api/wallets
Content-Type: application/json

{
  "name": "Guru G",
  "points": 300000,
  "phoneNumber": 9013087661
}

### to deposit the points
POST http://localhost:5000/api/wallets/6990f7a29cac5eea44770b05/deposit
Content-Type: application/json

{
  "points": 50000
}


### to withdraw the points
POST http://localhost:5000/api/wallets/6990f7a29cac5eea44770b05/withdraw
Content-Type: application/json

{
  "points": 100000
}


### to check the points
GET http://localhost:5000/api/wallets
Content-Type: application/json

